[package]
name = 'SimpleTortugaStrategy'
version = '1.0.0'

[addresses]
simple_tortuga_strategy = "0x659d53b22ebb61ef1f64d28698b8117f65136d8bb211d6d22f54d5064eec08f5"

[dependencies.satay]
git = "https://github.com/satay-protocol/satay-aptos"
rev = "main"

[dependencies.TortugaGovernance]
git = "https://github.com/satay-protocol/partner-interfaces"
rev = "testnet"
subdir = "tortuga-governance"

[dependencies.LiquidswapRouterV2]
git = 'https://github.com/pontem-network/liquidswap.git'
rev = 'main'
subdir = 'liquidswap_router_v2'